import pkg from 'ml-classify-text';
const { Classifier } = pkg;

// Preprocessing helper
function preprocess(text) {
  return text
    .toLowerCase()                      // lowercase
    .replace(/[^\w\s$!]/g, '')
    .replace(/\s+/g, ' ')               // normalize whitespace
    .trim();
}

// Initialize classifier with n-grams and vocabulary
const classifier = new Classifier({
  nGramMin: 1,
  nGramMax: 2,
});

// Training dataset (longer, realistic messages)
const trainingData = [
  // ---------------- SPAM ----------------
   { text: "Congratulations! You have been selected as the lucky winner of $5,000 cash. Reply with your bank details to claim.", label: "spam" },
  { text: "URGENT! Your account has been suspended. Verify immediately to avoid permanent closure.", label: "spam" },
  { text: "Earn $10,000 per week working from home! No experience required. Sign up today!", label: "spam" },
  { text: "Limited time offer! Buy one, get one free on all products. Claim your exclusive deal now.", label: "spam" },
  { text: "Your loan application is approved! Send personal details to receive funds within 24 hours.", label: "spam" },
  { text: "Get cheap prescription meds online. No doctor prescription needed. Order now!", label: "spam" },
  { text: "You have won a free iPhone! Claim it before this offer expires.", label: "spam" },
  { text: "Work from home and earn thousands per month. Sign up to start today!", label: "spam" },
  { text: "Exclusive deal! Save 70% on electronics this weekend only.", label: "spam" },
  { text: "You have an unclaimed reward waiting. Click the link to claim now.", label: "spam" },
  { text: "Act now! Your subscription is about to expire and will auto-renew.", label: "spam" },
  { text: "Make $5,000 weekly with our online system. No investment needed!", label: "spam" },
  { text: "Congratulations, you are selected for a special giveaway. Reply to claim!", label: "spam" },
  { text: "Immediate action required! Your bank account will be locked unless verified.", label: "spam" },
  { text: "Win big prizes by participating in our online survey today!", label: "spam" },
  { text: "Claim your free vacation package to the Bahamas. Limited slots available!", label: "spam" },
  { text: "Earn money fast with our side hustle program. Sign up now!", label: "spam" },
  { text: "Your PayPal account is at risk. Verify your identity immediately.", label: "spam" },
  { text: "Get rich quick with our step-by-step guide. Start earning today!", label: "spam" },
  { text: "Special promotion: Buy 2 get 1 free. Offer ends tonight!", label: "spam" },
  { text: "You are eligible for a cash bonus. Provide your details to receive it.", label: "spam" },
  { text: "Limited seats available for our online course. Enroll now!", label: "spam" },
  { text: "Free trial for premium membership. Sign up and enjoy benefits.", label: "spam" },
  { text: "Urgent: Your account will be suspended in 24 hours. Take action now.", label: "spam" },
  { text: "Earn passive income online with our simple platform. Join today!", label: "spam" },
  { text: "Act fast! Your coupon code expires tonight. Claim your discount.", label: "spam" },
  { text: "You are a lucky winner of our monthly lottery. Reply to claim your prize.", label: "spam" },
  { text: "Your subscription has expired. Renew now to avoid losing access.", label: "spam" },
  { text: "Congratulations! Claim your free Amazon gift card now.", label: "spam" },
  { text: "Your account shows suspicious activity. Verify immediately to avoid closure.", label: "spam" },
  { text: "Make $500 daily from home using our tested method. Sign up today!", label: "spam" },
  { text: "Get a free gift card when you complete this short survey today!", label: "spam" },
  { text: "URGENT: Your email account has been compromised. Reset your password now!", label: "spam" },
  { text: "Limited-time investment opportunity. Double your money in 30 days!", label: "spam" },
  { text: "Congratulations! You have won tickets to the Super Bowl. Claim now.", label: "spam" },
  { text: "Get a free iPad! Just pay shipping and handling fees today.", label: "spam" },
  { text: "Exclusive online offer! Buy one, get one free for 24 hours only.", label: "spam" },
  { text: "Your account will be permanently deleted unless verified immediately.", label: "spam" },
  { text: "Win a brand-new car! Participate in our online raffle today!", label: "spam" },
  { text: "Congratulations! You’ve been selected for a $1000 gift card reward.", label: "spam" },
  { text: "Urgent: Verify your credit card to avoid service interruption.", label: "spam" },
  { text: "Get paid to watch videos online. Sign up and start earning today!", label: "spam" },
  { text: "You have an unclaimed reward. Click here to collect now!", label: "spam" },
  { text: "Work from home and earn $3000 per month! Start today!", label: "spam" },
  { text: "Special offer! Free trial for our premium service. Sign up now.", label: "spam" },
  { text: "Earn cash fast with this simple online program. Register today.", label: "spam" },
  { text: "Your PayPal account requires urgent verification. Click to confirm.", label: "spam" },
  { text: "Win an all-expense-paid vacation. Respond immediately to claim!", label: "spam" },
  { text: "Limited-time discount! Save 50% on all items for the next 24 hours.", label: "spam" },
  { text: "Congratulations! You are the winner of our exclusive monthly lottery.", label: "spam" },
  { text: "Urgent action required! Your account will be blocked if not verified.", label: "spam" },
  { text: "Make money online fast! Sign up for our exclusive program today.", label: "spam" },
  { text: "Claim your free subscription to our premium newsletter now!", label: "spam" },
  { text: "Get instant access to our online course and boost your income.", label: "spam" },
  { text: "Your account shows unusual activity. Confirm identity immediately.", label: "spam" },
  { text: "Win cash prizes by completing our online survey today!", label: "spam" },
  { text: "Limited offer! Buy two products and get one free. Today only.", label: "spam" },
  { text: "Immediate verification needed for your account. Act now!", label: "spam" },
  { text: "Congratulations! Claim your $500 gift card before it expires.", label: "spam" },
  { text: "Earn thousands per week from home with no experience required.", label: "spam" },
  { text: "URGENT: Your bank account has been compromised. Verify now!", label: "spam" },
  { text: "Get a free smartphone today! Only pay shipping. Limited offer.", label: "spam" },
  { text: "Your account is at risk. Confirm your identity immediately.", label: "spam" },
  { text: "Limited-time offer: Free eBook when you sign up now.", label: "spam" },
  { text: "You have been selected for a $2000 bonus! Claim immediately.", label: "spam" },
  { text: "Work from home and earn $5000 per month! Start today.", label: "spam" },
  { text: "Congratulations! You are our lucky winner. Reply to claim your prize.", label: "spam" },
  { text: "Act fast! Your exclusive discount expires today. Shop now.", label: "spam" },
  { text: "Urgent: Your account will be closed unless verified immediately.", label: "spam" },
  { text: "Make money online quickly with our easy step-by-step system.", label: "spam" },
  { text: "You are eligible for a free gift card. Click here to claim.", label: "spam" },
  { text: "Win a luxury vacation! Respond now to secure your spot.", label: "spam" },
  { text: "Limited seats! Register for our online seminar today and save.", label: "spam" },
  { text: "Congratulations! Claim your free Amazon voucher today.", label: "spam" },
  { text: "Your subscription will expire soon. Renew immediately.", label: "spam" },
  { text: "Earn money from home with our proven online platform. Sign up!", label: "spam" },
  { text: "Urgent notice: Verify your account to avoid permanent closure.", label: "spam" },
  { text: "Win a brand-new laptop! Enter our contest today.", label: "spam" },
  { text: "Immediate action required! Your email account is at risk.", label: "spam" },
  { text: "Get paid to complete surveys online. Join now!", label: "spam" },
  { text: "Claim your $1000 bonus now! Limited slots available.", label: "spam" },
  { text: "Work from home and earn extra income. Sign up today!", label: "spam" },
  { text: "Special online offer! Get 50% off premium products today.", label: "spam" },
  { text: "Your account has suspicious activity. Confirm identity immediately.", label: "spam" },
  { text: "Congratulations! You have won our monthly prize draw.", label: "spam" },
  { text: "Limited-time bonus! Claim your free membership now.", label: "spam" },
  { text: "Urgent: Your bank account needs verification. Act now!", label: "spam" },
  { text: "Earn money fast with our exclusive online system. Join today!", label: "spam" },
  { text: "Get a free tablet today! Limited offer, pay shipping only.", label: "spam" },
  { text: "You have been selected for an exclusive reward. Claim now.", label: "spam" },
  { text: "Win big prizes today! Enter our online sweepstakes now.", label: "spam" },
  { text: "Congratulations! You are the lucky winner of our special offer.", label: "spam" },
  { text: "Immediate action required! Your subscription is about to expire.", label: "spam" },
  { text: "Earn thousands from home with our step-by-step program.", label: "spam" },
  { text: "Claim your free digital product today. Limited offer.", label: "spam" },
  { text: "Urgent: Your account will be suspended if not verified today.", label: "spam" },
  { text: "Make $1000 per week online with our proven system. Start now!", label: "spam" },
  { text: "Get a free smartwatch! Pay shipping only. Claim today.", label: "spam" },
  { text: "Your account requires verification to avoid closure.", label: "spam" },
  { text: "Congratulations! You are selected for our exclusive online prize.", label: "spam" },
  { text: "Act fast! Claim your free membership before the offer ends.", label: "spam" },
  { text: "Urgent: Verify your email account immediately to prevent suspension.", label: "spam" },
  { text: "Earn passive income with our online platform. Join now!", label: "spam" },
  { text: "Win a free vacation! Limited slots available. Register today.", label: "spam" },
  { text: "Congratulations! Claim your free online course today.", label: "spam" },
  { text: "Your bank account shows unusual activity. Verify immediately.", label: "spam" },
  { text: "Get paid to watch ads online. Sign up now and start earning!", label: "spam" },
  { text: "Immediate action required! Claim your reward before it expires.", label: "spam" },
  { text: "Limited offer! Buy our product today and get a free bonus.", label: "spam" },
  { text: "You are a lucky winner of our online raffle. Respond to claim.", label: "spam" },
  { text: "Act now! Your exclusive prize is waiting. Click to claim.", label: "spam" },
  { text: "URGENT: Your subscription will expire in 24 hours. Renew now.", label: "spam" },
  { text: "Earn money fast from home using our online system. Sign up today.", label: "spam" },
  { text: "Win instant cash prizes! Participate in our online contest now.", label: "spam" },
  { text: "Congratulations! You’ve been selected for a free digital gift card.", label: "spam" },
  { text: "Your account is at risk. Verify your identity immediately.", label: "spam" },
  { text: "Limited-time bonus! Sign up for our exclusive offer today.", label: "spam" },
  { text: "Claim your free subscription to our premium service now.", label: "spam" },
  { text: "Work from home and earn $2000 per week! Register today.", label: "spam" },
  { text: "Congratulations! You are the winner of our monthly sweepstakes.", label: "spam" },
  { text: "Urgent: Verify your email to avoid account suspension.", label: "spam" },
  { text: "Get instant access to our online program and start earning today.", label: "spam" },
  { text: "Your PayPal account is at risk. Confirm immediately.", label: "spam" },
  { text: "Win a free gadget! Limited-time offer, respond today.", label: "spam" },
  { text: "Act fast! Your exclusive reward is about to expire.", label: "spam" },
  { text: "Earn thousands of dollars from home with our online system.", label: "spam" },
  { text: "Immediate verification needed for your account. Click now.", label: "spam" },
  { text: "Congratulations! Claim your free digital product today.", label: "spam" },
  { text: "Your subscription is about to expire. Renew immediately.", label: "spam" },
  { text: "Limited-time offer! Get your free trial of our premium service.", label: "spam" },

  // ---------------- HAM ----------------
{ text: "Hi John, just checking if you can join the team call tomorrow at 10 AM.", label: "ham" },
{ text: "Happy birthday, Emily! Wishing you a wonderful day filled with joy.", label: "ham" },
{ text: "Your package has been shipped and will arrive within 3 business days.", label: "ham" },
{ text: "Reminder: The project deadline is this Friday. Please submit your updates.", label: "ham" },
{ text: "Dear team, please find attached the quarterly report for review.", label: "ham" },
{ text: "Hey Mike, are we still on for lunch tomorrow?", label: "ham" },
{ text: "Your appointment with Dr. Smith is confirmed for Monday at 3 PM.", label: "ham" },
{ text: "Can you send me the updated budget spreadsheet before our call?", label: "ham" },
{ text: "Thanks for your help on the report yesterday. Much appreciated!", label: "ham" },
{ text: "Let’s schedule a catch-up over coffee next week. Are you free?", label: "ham" },
{ text: "Looking forward to seeing you at the conference next month.", label: "ham" },
{ text: "Please review the attached presentation and provide feedback.", label: "ham" },
{ text: "I will be on leave next Wednesday. Please plan accordingly.", label: "ham" },
{ text: "Thank you for attending the workshop. Your participation was valuable.", label: "ham" },
{ text: "Can we discuss the project updates tomorrow over Zoom?", label: "ham" },
{ text: "Happy holidays to you and your family! Wishing you a joyful season.", label: "ham" },
{ text: "Please find the invoice attached for your review and approval.", label: "ham" },
{ text: "Your Zoom link for tomorrow’s meeting is ready. Please check your email.", label: "ham" },
{ text: "Thanks for your quick response to the client’s query.", label: "ham" },
{ text: "Looking forward to our collaboration on the new project.", label: "ham" },
{ text: "Hope you had a great weekend! Let’s catch up soon.", label: "ham" },
{ text: "I will send you the updates by the end of the day.", label: "ham" },
{ text: "Can we postpone the meeting to Friday? Let me know your thoughts.", label: "ham" },
{ text: "Congratulations on your promotion! Well deserved.", label: "ham" },
{ text: "The quarterly performance report is attached for your review.", label: "ham" },
{ text: "Please review the attached document and provide feedback.", label: "ham" },
{ text: "Your appointment has been rescheduled to Thursday at 11 AM.", label: "ham" },
{ text: "Can you confirm your attendance for the workshop next week?", label: "ham" },
{ text: "Hey Sarah, it was great catching up over coffee last week!", label: "ham" },
{ text: "Don’t forget to submit your timesheet by the end of the day.", label: "ham" },
{ text: "Please share your feedback on the draft proposal.", label: "ham" },
{ text: "Your subscription to the newsletter has been successfully renewed.", label: "ham" },
{ text: "Reminder: Team outing scheduled for Friday at 6 PM.", label: "ham" },
{ text: "Can you check if the client received the package?", label: "ham" },
{ text: "Your flight booking is confirmed for next Monday.", label: "ham" },
{ text: "Hey, are we still on for the tennis match this weekend?", label: "ham" },
{ text: "The client meeting has been moved to Thursday. Please update your calendar.", label: "ham" },
{ text: "Please review the attached document and let me know your comments.", label: "ham" },
{ text: "Your reservation at the restaurant is confirmed for 7 PM tomorrow.", label: "ham" },
{ text: "The software update will be applied tonight after business hours.", label: "ham" },
{ text: "Please complete the online training by the end of this week.", label: "ham" },
{ text: "Can you provide the latest sales figures by EOD?", label: "ham" },
{ text: "Your order has been delivered. Please check your package.", label: "ham" },
{ text: "Happy anniversary, Mark! Wishing you and Jane all the best.", label: "ham" },
{ text: "Can we reschedule our one-on-one meeting to Wednesday?", label: "ham" },
{ text: "Please find the meeting agenda attached for tomorrow’s call.", label: "ham" },
{ text: "Thanks for confirming your attendance at the training session.", label: "ham" },
{ text: "Your hotel booking is confirmed. Check-in is at 3 PM.", label: "ham" },
{ text: "Please let me know if you need any assistance with the project.", label: "ham" },
{ text: "Reminder: Submit your project updates before the weekly review.", label: "ham" },
{ text: "Looking forward to your presentation at the conference next week.", label: "ham" },
{ text: "Hey Lisa, it was great seeing you yesterday. Want to grab lunch this week?", label: "ham" },
{ text: "Please review the attached contract and share your feedback.", label: "ham" },
{ text: "The invoice has been processed and payment will be made by Friday.", label: "ham" },
{ text: "Your library books are due tomorrow. Please return them on time.", label: "ham" },
{ text: "Reminder: Staff meeting is scheduled for 9 AM Monday.", label: "ham" },
{ text: "Can you check if the server backup completed successfully?", label: "ham" },
{ text: "Thanks for your input on the design mockups.", label: "ham" },
{ text: "Your credit card statement is now available online.", label: "ham" },
{ text: "Please RSVP for the company holiday party by Friday.", label: "ham" },
{ text: "The parking permit has been approved. You can collect it from reception.", label: "ham" },
{ text: "Can we move our meeting to 2 PM instead of 11 AM?", label: "ham" },
{ text: "Your subscription renewal is confirmed for the next 12 months.", label: "ham" },
{ text: "Please confirm your attendance for the upcoming webinar.", label: "ham" },
{ text: "Your application has been successfully submitted.", label: "ham" },
{ text: "Thanks for sharing the updated project files.", label: "ham" },
{ text: "Hey, just wanted to check if you received my last email.", label: "ham" },
{ text: "Reminder: Submit your expense reports by Friday.", label: "ham" },
{ text: "Your package has been delayed due to shipping issues.", label: "ham" },
{ text: "Please provide your feedback on the customer survey.", label: "ham" },
{ text: "The meeting room has been booked for 3 PM tomorrow.", label: "ham" },
{ text: "Can you share the presentation slides from today’s meeting?", label: "ham" },
{ text: "Thank you for confirming your participation in the event.", label: "ham" },
{ text: "Your subscription to the service has been successfully activated.", label: "ham" },
{ text: "Hey Tom, can we reschedule our call to Thursday?", label: "ham" },
{ text: "Please update the project plan with the latest timelines.", label: "ham" },
{ text: "The invoice has been sent to the client for approval.", label: "ham" },
{ text: "Reminder: Your car service appointment is scheduled for Friday at 10 AM.", label: "ham" },
{ text: "Thanks for attending the client meeting today.", label: "ham" },
{ text: "Your ticket to the concert is confirmed. Enjoy the show!", label: "ham" },
{ text: "Please check the attached spreadsheet and verify the data.", label: "ham" },
{ text: "Can you provide an update on the pending tasks?", label: "ham" },
{ text: "Your room booking at the hotel has been successfully confirmed.", label: "ham" },
{ text: "Hey, I’ve shared the link to the document in the team chat.", label: "ham" },
{ text: "Reminder: Submit your quarterly review by Friday.", label: "ham" },
{ text: "Thanks for sending the requested information.", label: "ham" },
{ text: "Your library membership has been renewed for another year.", label: "ham" },
{ text: "Please review the attached proposal and share your comments.", label: "ham" },
{ text: "Your appointment with Dr. Lee is confirmed for next Monday.", label: "ham" },
{ text: "Can we meet next week to discuss the project requirements?", label: "ham" },
{ text: "The tickets for the workshop are now available. Please register.", label: "ham" },
{ text: "Thanks for your feedback on the draft report.", label: "ham" },
{ text: "Please update the task status in the project management tool.", label: "ham" },
{ text: "Your payment has been successfully processed.", label: "ham" },
{ text: "Hey, just checking if you received the invitation for the webinar.", label: "ham" },
{ text: "Reminder: Team lunch scheduled for Wednesday at 1 PM.", label: "ham" },
{ text: "Your package has been shipped via FedEx and will arrive tomorrow.", label: "ham" },
{ text: "Please review the attached email chain for context.", label: "ham" },
{ text: "Thanks for confirming the meeting time.", label: "ham" },
{ text: "Your subscription has been successfully renewed for another year.", label: "ham" },
{ text: "Hey, are you available for a quick call this afternoon?", label: "ham" },
{ text: "Please find attached the minutes from yesterday’s meeting.", label: "ham" },
{ text: "The conference registration has been completed successfully.", label: "ham" },
{ text: "Can you share the final version of the report?", label: "ham" },
{ text: "Your hotel reservation has been confirmed for next weekend.", label: "ham" },
{ text: "Thanks for reviewing the document and providing feedback.", label: "ham" },
{ text: "Reminder: Submit your project deliverables by Monday.", label: "ham" },
{ text: "Your subscription to the newsletter has been updated successfully.", label: "ham" },
{ text: "Please confirm the meeting time for next Thursday.", label: "ham" },
{ text: "Hey Alex, it was nice seeing you yesterday. Let’s catch up soon.", label: "ham" },
{ text: "The report has been finalized and sent to the client.", label: "ham" },
{ text: "Your car service appointment has been successfully scheduled.", label: "ham" },
{ text: "Can you review the attached presentation before tomorrow’s meeting?", label: "ham" },
{ text: "Thanks for providing the updated information.", label: "ham" },
{ text: "Your registration for the online course is confirmed.", label: "ham" },
{ text: "Hey, just wanted to check if you’re free for a quick chat today.", label: "ham" },
{ text: "Please review the attached budget and let me know your thoughts.", label: "ham" },
{ text: "The maintenance work will be carried out tonight from 10 PM.", label: "ham" },
{ text: "Thanks for confirming the project timeline.", label: "ham" },
{ text: "Your subscription has been successfully activated.", label: "ham" },
{ text: "Can you share the client feedback from yesterday’s meeting?", label: "ham" },
{ text: "Hey, I’ve added you to the project group on Slack.", label: "ham" },
{ text: "Reminder: Submit your travel expenses by Friday.", label: "ham" },
{ text: "Your appointment with Dr. Wilson is confirmed for Tuesday.", label: "ham" },
{ text: "Please find the attached agenda for the upcoming team call.", label: "ham" },
{ text: "Thanks for sharing the updated client requirements.", label: "ham" },
{ text: "Your flight itinerary has been confirmed and sent via email.", label: "ham" },
{ text: "Hey, can we move our meeting to 3 PM instead of 1 PM?", label: "ham" },
{ text: "Please review the attached contract and provide your comments.", label: "ham" },
{ text: "The tickets for the seminar are now available. Register soon.", label: "ham" },
{ text: "Thanks for updating the project status in the system.", label: "ham" },
{ text: "Your invoice has been processed and payment is on its way.", label: "ham" },
{ text: "Hey, just checking if you received the latest project files.", label: "ham" }
];


// Train classifier
trainingData.forEach(({ text, label }) => {
  if (!label || typeof label !== 'string') {
    throw new Error(`Invalid label for text: "${text}"`);
  }
  classifier.train(preprocess(text), label.trim());
});

// Predict function
export function checkSpam(message) {
  const preprocessed = preprocess(message);
  const results = classifier.predict(preprocessed);

  let result;

  if (results && results.length > 0) {
    // Pick the one with highest confidence
    result = results.reduce((max, r) => (r.confidence > max.confidence ? r : max), results[0]);
  } else {
    // If no result, mark as suspicious
    return { label: 'suspicious', score: 0.1 };
  }

  const { label, confidence } = result;

  // Decide label based on confidence thresholds
  // You can adjust these thresholds
  if (confidence >= 0.6) {
    // strong prediction
    return { label, score: confidence };
  } else {
    // not confident enough, mark suspicious
    return { label: 'suspicious', score: confidence };
  }
}


export default classifier;

